@startuml
'Domænemodellen giver nye entity klasser
'Pakker, model og util
!pragma layout smetana

class Main
class StartMenu
class MainMenu

class CreateAccount
class User
class DataValidator

Abstract Settings

class Laundry
class Market
class Wardrobe
class ErrorHandling
class Category

class CreateUserSettings
class NotificationSettings

Abstract Clothing
class Pant
class Shirt
class Shoes
class Socks
class underwear

package "util"{
       class TextUI
       class DbIO
       }
Main *-- StartMenu
StartMenu *-- MainMenu
MainMenu *-- Settings
MainMenu *-- Laundry
MainMenu *-- Market
MainMenu *-- Wardrobe
MainMenu *-- ErrorHandling
Wardrobe *-- Category

User *-- DataValidator
User *-- CreateAccount
Settings *-- CreateUserSettings
Settings *-- NotificationSettings
Clothing *-- Wardrobe
Clothing *-- Shoes
Clothing *-- Shirt
Clothing *-- Pants
Clothing *-- Socks
Clothing *-- Underwear
Clothing *-- Pan

StartMenu : + login()
StartMenu : + createUser()

MainMenu : + Wardrobe
MainMenu : + Laundry
MainMenu : + Market
MainMenu : + Settings
MainMenu : + ErrorHandling

Clothing : + String color
Clothing : + String brand
Clothing : + String type
Clothing : + String Seasons

Shoes : + String type
Shoes : + float size

Shirt : + String Sleeves length
Shirt : + String neck
Shirt : + String type

Pants : + String shorts
Pants : + String Jeans
Pants : + String size
Pants : + boolean pockets

Socks : + String size
Socks : + String type

Underwear : + String size
Underwear : + String material
Underwear : + String type

Market : + sellClothing()
Market : + buyClothing()
Market : + donateClothing()
Market : + borrowClothing()
Market : + addToBuyHistory()
Market : + addToSellHistory()
Market : + chatWindow()
Market : + savedListing()

Wardrobe : + createOutfit()
Wardrobe : + generateOutfit()
Wardrobe : + showPreWornOutfits()
Wardrobe : + addOutfitToFavorite()
Wardrobe : + addClothingToWardrobe()
Wardrobe : + removeClothingFromWardrobe()
Wardrobe : + addClothingToLaundry()

Settings : + createUserSettings()
Settings : + notificationSettings()
Settings : + logOut()
Settings : + EULA()

Laundry : + view()
Laundry : + empty()
Laundry : + removeFromBasket()


Main : + static void main(string [] args)

User : - String username
User : - String password
User : - static ArrayList <User> users
'---_new-----
User : + User(String Username, String Password)
'-----------

'---_new-----
DataValidator : + Boolean isUsernameValid()
DataValidator : + Boolean isPassWordValid()
'-----------

CreateAccount : - Boolean createUser(String name, String Password)
CreateAccount : - Boolean addUser(new user(name, Password)
CreateAccount : - Boolean removeUser(new user(name, Password)


DbIO : - Scanner scanner

'---_new-----
DbIO : + Arraylist<User> readUserData(String path)
DbIO : + void saveUserData(ArrayList<User> users)
DbIO : + String[] readLoginData(String Username, String password)
DbIO : + String[] readMediaData(String title, int releaseYear, float rating, String genre)
'-----------

TextUI : + String getInput(String msg)
TextUI : - Scanner scanner
TextUI : + void displayMessage(String msg)

@enduml